openapi: 3.0.1

info:
  title: Table Detection
  description: Table detection using OpenCV
  version: 1.0.0
  
servers:
  - url: /

paths:
  /detect_table:
    post:
      tags: 
        - Table
      summary: detect table structure
      requestBody:
        required: true
        description: provide image url
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
      responses:
        200:
          description: success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableSchema"
        400:
          description: invalid url.
        404:
          description: file not found.
        422:
          description: request not processable.
        500:
          description: internal server error. 
              
              
components:
  schemas:
    RequestSchema:
      properties:
        image_url:
          type: string
    Coordinates:
      properties:
        x_start:
          type: string
        x_end:
          type: string
        y_start:
          type: string
        y_end:
          type: string
    Table:
      properties:
        columns:
          type: array
          items:
            properties:
              column:
                $ref: "#/components/schemas/Coordinates"
        rows:
          type: array
          items:
            properties:
              row:
                $ref: "#/components/schemas/Coordinates"
    TableSchema:
      properties:
        image_url:
          type: string
        tables:
          type: array
          items:
              properties:
                table:
                  $ref: "#/components/schemas/Table"
