openapi: 3.0.1

info:
  title: Table Detection
  description: Table detection using OpenCV
  version: 1.0.0
  
servers:
  - url: /

paths:
  /detect_table:
    post:
      tags: 
        - Table
      summary: detect table structure
      requestBody:
        required: true
        description: provide image url
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TableSchema"
      responses:
        200:
          description: success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TableSchema"
        400:
          description: invalid url.
        404:
          description: file not found.
        422:
          description: request not processable.
        500:
          description: internal server error. 
              
              
components:
  schemas:
    TableSchema:
      properties:
        image_url:
          type: string
