apiVersion: apps/v1

kind: Deployment

metadata:
  name: table-detection-deployment
  labels:
    app: table-detection

spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: table-detection
  template:
    metadata:
      labels:
        app: table-detection
    spec:
      containers:
        - name: table-detection-container
          image: ck1998/table_detection_app_image:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000 